app/routes/routes.py
from flask import Blueprint, jsonify, request, session, url_for, redirect, flash, render_template
from ..controllers import MovieController, AuthController
from functools import wraps

# decorator to limit access to protected pages
# only login user can access
def login_required(f):
    @wraps(f)
    def wrapper(*args, **kwargs):
        if 'userId' not in session:
            return redirect(url_for('auth.login', next=request.url))
        return f(*args, **kwargs)
    return wrapper

# only admin user can access
def admin_required(f):
    @login_required
    @wraps(f)
    def wrapper(*args, **kwargs):
        if session.get('userType') != 'admin':
            flash("You do not have the required permissions to access this page.")
            return redirect(url_for('movies.home'))
        return f(*args, **kwargs)
    return wrapper

# only customer can access
def customer_required(f):
    @login_required
    @wraps(f)
    def wrapper(*args, **kwargs):
        if session.get('userType') != 'customer':
            flash("You do not have the required permissions to access this page.")
            return redirect(url_for('movies.home'))
        return f(*args, **kwargs)
    return wrapper


movie_bp = Blueprint('movies', __name__)
auth_bp = Blueprint('auth', __name__)

# home page
@movie_bp.route('/', methods=['GET'])
def home():
    return MovieController.browseMovies()

# browse all movies or search for movies
@movie_bp.route('/movies', methods = ['GET', 'POST'])
def showMovies():
    title = request.args.get('title')
    year = request.args.get('year')
    language = request.args.get('language')
    genre = request.args.get('genre')
    if title:
        return MovieController.searchMovies("title", title)
    elif year:
        return MovieController.searchMovies("year", int(year))
    elif language:
        return MovieController.searchMovies("language", language)
    elif genre:
        return MovieController.searchMovies("genre", genre)
    else:
        return MovieController.browseMovies()
    
# display a movie's details and screenings
@movie_bp.route('/movies/<movieId>', methods=['GET', 'POST'])
def showMovieDetailsAndScreenings(movieId):
    return MovieController.viewMovieDetailsAndScreenings(movieId)


# display a screening's seat charts
@movie_bp.route('/book/<screeningId>/seats', methods=['GET', 'POST'])
@login_required
def selectSeats(screeningId):
    if request.method == 'POST':
        selectedSeatIds = request.form.getlist('selectedSeatIds')
        return MovieController.processBooking(session['userId'], screeningId=screeningId, selectedSeatIds=selectedSeatIds)   
    return MovieController.viewSeatChart(screeningId)

# if 'GET', display payment page; if 'POST', get payment information and process booking
@movie_bp.route('/book/<bookingId>/payment/online', methods=['GET', 'POST'])
@customer_required
def paymentOnline(bookingId):
    if request.method == 'POST':
        paymentMethod = request.form.get('paymentMethod')
        couponCode = request.form.get('couponCode')
        paymentData = {
            'bookingId': bookingId,
            'paymentMethod': paymentMethod,
            'couponCode': couponCode
        }

        if paymentMethod == 'creditcard':
            paymentData['creditCardNumber'] = request.form.get('creditCardNumber')
            paymentData['expiryDate'] = request.form.get('expiryDate')
            paymentData['nameOnCard'] = request.form.get('nameOnCard')

        elif paymentMethod == 'debitcard':
            paymentData['debitCardNumber'] = request.form.get('debitCardNumber')
            paymentData['bankName'] = request.form.get('bankName')
            paymentData['nameOnCard'] = request.form.get('nameOnCard')

        return MovieController.processBooking(session['userId'], paymentData=paymentData)
    return MovieController.showPaymentPageOnline(bookingId=bookingId)

@movie_bp.route('/book/<bookingId>/payment/onsite', methods=['GET', 'POST'])
@login_required
def paymentOnsite(bookingId):
    if request.method == 'POST':
        paymentMethod = request.form.get('paymentMethod')
        couponCode = request.form.get('couponCode')

        if paymentMethod == 'cash':
            paymentData = {
                'bookingId': bookingId,
                'paymentMethod': paymentMethod,
                'receivedCash': request.form.get('receivedCash'),
                'change': request.form.get('change'),
                'couponCode': couponCode
            }
            print(paymentData)

        elif paymentMethod == 'eftpos':
            paymentData = {
                'bookingId': bookingId,
                'paymentMethod': paymentMethod,
                'couponCode': couponCode
            }

        return MovieController.processBooking(session['userId'], paymentData=paymentData)
    return MovieController.showPaymentPageOnsite(bookingId=bookingId)

# get data from javascript code to validate coupon
@movie_bp.route('/api/validate-coupon', methods=['POST'])
def validateCoupon():
    data = request.json
    couponCode = data.get('couponCode')
    return MovieController.validateCouponCode(couponCode)

# display booking confirmation page
@movie_bp.route('/book/<bookingId>/confirm', methods=['GET'])
@login_required
def confirmBooking(bookingId):
    return MovieController.confirmBooking(bookingId=bookingId)

# check all bookings
@movie_bp.route('/bookings', methods=['GET'])
@login_required
def viewBookings():
    return MovieController.viewBookings(session['userId'])

# cancel booking
@movie_bp.route('/cancel/<bookingId>', methods=['POST'])
@login_required
def cancelBooking(bookingId):
    return MovieController.cancelBooking(session['userId'], bookingId)

# if 'GET', display add movie page; if 'POST', get data from input and add a movie
@movie_bp.route('/add/movie', methods=['GET', 'POST'])
@admin_required
def addMovie():
    if request.method == 'POST':
        newMovieData = {
            "title": request.form.get('title'),
            "language": request.form.get('language'),
            "genre": request.form.get('genre'),
            "releaseDate": request.form.get('releaseDate'),
            "durationMins": request.form.get('durationMins'),
            "country": request.form.get('country'),
            "description": request.form.get('description')
        }
        return MovieController.addMovie(session['userId'], newMovieData)
    return MovieController.showAddMoviePage()

# add screening
@movie_bp.route('/add/movie/<movieId>/screening', methods=['POST'])
@admin_required
def addScreening(movieId):
    newScreeningData = {
        "screeningDate": request.form.get('screeningDate'),
        "startTime": request.form.get('startTime'),
        "endTime": request.form.get('endTime'),
        "hallId": request.form.get('hallId'),
        "movieId": movieId
    }
    return MovieController.addScreening(session['userId'], newScreeningData) 

# cancel movie
@movie_bp.route('/cancel/movie', methods=['GET'])
@movie_bp.route('/cancel/movie/<movieId>', methods=['GET', 'POST'])
@admin_required
def cancelMovie(movieId=None):
    if movieId and request.method == 'POST':
        return MovieController.cancelMovie(session['userId'], movieId)
    elif movieId:
        return redirect(url_for('movies.showMovieDetails',movieId=movieId))
    else:
        return MovieController.showCancelMoviePage()
    
# cancel screening
@movie_bp.route('/cancel/screening/<screeningId>', methods=['POST'])
@admin_required
def cancelScreening(screeningId):
    return MovieController.cancelScreening(session['userId'], screeningId)

# work together with javascript code to get notification
@movie_bp.route('/api/get-notifications')
@customer_required
def getNotifications():
    return MovieController.getNotifications(session['userId'])

# work together with javascript code to mark notificaton
@movie_bp.route('/api/mark-notification-read', methods=['POST'])
def markNotificationRead():
    notificationId = request.form['id']
    return MovieController.markNotificationRead(notificationId)

# display sign up page if 'GET' and sign up if 'POST'
@auth_bp.route('/signup', methods=['GET', 'POST'])
def signup():
    if request.method == 'POST':
        username = request.form.get('username')
        password = request.form.get('password')
        return AuthController.register(username, password)
    return AuthController.showSignup()

# display login page if 'GET' and login if 'POST'
@auth_bp.route('/login', methods = ['GET', 'POST'])
def login():
    if request.method == 'POST':
        username = request.form.get('username')
        password = request.form.get('password')
        return AuthController.login(username, password)
    return AuthController.showLogin()

# logout
@auth_bp.route('/logout', methods=['GET', 'POST'])
@login_required
def logout():
    return AuthController.logout()











    

app/templates/addMovie.html
{% extends 'base.html' %}

{% block title %}My bookings{% endblock %}

{% block content %}

<div class="container mx-auto mt-20 p-8 w-2/5 bg-white rounded-lg shadow-xl">
    <h2 class="text-3xl mb-6 font-semibold text-center text-gray-800">Add a New Movie</h2>

    <form action="{{ url_for('movies.addMovie') }}" method="post" enctype="multipart/form-data" class="space-y-6">

        <!-- Movie Title -->
        <div class="w-full px-3 mb-4">
            <label class="block uppercase tracking-wide text-gray-600 text-xs font-bold mb-2" for="title">Movie Title</label>
            <input name="title" id="title" type="text" required class="appearance-none block w-full bg-gray-100 text-gray-700 rounded py-3 px-4 leading-tight focus:outline-none focus:bg-white focus:border-gray-500">
        </div>

        <!-- Genre -->
        <div class="w-full px-3 mb-4">
            <label class="block uppercase tracking-wide text-gray-600 text-xs font-bold mb-2" for="genre">Genre</label>
            <input name="genre" id="genre" type="text" required class="appearance-none block w-full bg-gray-100 text-gray-700 rounded py-3 px-4 leading-tight focus:outline-none focus:bg-white focus:border-gray-500">
        </div>

        <!-- Language, Release Date -->
        <div class="flex flex-wrap -mx-3 mb-4">
            <div class="w-full md:w-1/2 px-3 mb-4 md:mb-0">
                <label class="block uppercase tracking-wide text-gray-600 text-xs font-bold mb-2" for="language">Language</label>
                <input name="language" id="language" type="text" class="appearance-none block w-full bg-gray-100 text-gray-700 rounded py-3 px-4 leading-tight focus:outline-none focus:bg-white focus:border-gray-500">
            </div>
            <div class="w-full md:w-1/2 px-3 mb-4 md:mb-0">
                <label class="block uppercase tracking-wide text-gray-600 text-xs font-bold mb-2" for="releaseDate">Release Date</label>
                <input name="releaseDate" id="releaseDate" type="date" class="appearance-none block w-full bg-gray-100 text-gray-700 rounded py-3 px-4 leading-tight focus:outline-none focus:bg-white focus:border-gray-500">
            </div>
        </div>

        <!-- Duration, Country -->
        <div class="flex flex-wrap -mx-3 mb-4">
            <div class="w-full md:w-1/2 px-3 mb-4 md:mb-0">
                <label class="block uppercase tracking-wide text-gray-600 text-xs font-bold mb-2" for="durationMins">Duration (Mins)</label>
                <input name="durationMins" id="durationMins" type="number" class="appearance-none block w-full bg-gray-100 text-gray-700 rounded py-3 px-4 leading-tight focus:outline-none focus:bg-white focus:border-gray-500">
            </div>
            <div class="w-full md:w-1/2 px-3">
                <label class="block uppercase tracking-wide text-gray-600 text-xs font-bold mb-2" for="country">Country</label>
                <input name="country" id="country" type="text" class="appearance-none block w-full bg-gray-100 text-gray-700 rounded py-3 px-4 leading-tight focus:outline-none focus:bg-white focus:border-gray-500">
            </div>
        </div>

        <!-- Description -->
        <div class="w-full px-3 mb-4">
            <label class="block uppercase tracking-wide text-gray-600 text-xs font-bold mb-2" for="description">Description</label>
            <textarea name="description" id="description" rows="4" class="appearance-none block w-full bg-gray-100 text-gray-700 rounded py-3 px-4 leading-tight focus:outline-none focus:bg-white focus:border-gray-500"></textarea>
        </div>

        <!-- Poster Upload -->
        <div class="w-full px-3 mb-4">
            <label class="block uppercase tracking-wide text-gray-600 text-xs font-bold mb-2" for="poster">Movie Poster</label>
            <input name="poster" id="poster" type="file" class="appearance-none block w-full bg-gray-100 text-gray-700 py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white focus:border-gray-500">
        </div>

        <button type="submit" class="mt-4 bg-gray-800 hover:bg-gray-700 text-white font-bold py-2 px-4 rounded">
            Add Movie
        </button>
    </form>
</div>

{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600&display=swap" rel="stylesheet">
    <link href="/static/output.css" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <title>{% block title %}{% endblock %}</title>
</head>

<body class="bg-gradient-to-r from-purple-400 via-pink-500 to-red-500 h-screen">

  <!-- The content of pages.-->
  <header>
    {% block header %}{% endblock %}
  </header>

  <!-- Navbar -->
  <nav class="bg-primary p-4 text-white font-poppins">
    <div class="container mx-auto">
        <div class="flex justify-between items-center">
            <a href="/" class="text-3xl font-bold">Lincoln Cinema</a>
            <div class="space-x-4">
                <a href="{{ url_for('movies.showMovies')}}" class="hover:bg-gray-600 hover:bg-opacity-50 px-3 py-2 rounded transition">Movies</a>

                {% if session['userId'] %}
                    {% if session['userType'] == 'customer' %}
                        <a href="{{ url_for('movies.viewBookings')}}" class="hover:bg-gray-600 hover:bg-opacity-50 px-3 py-2 rounded transition">My bookings</a>

                        <!-- Notification icon with potential red dot for unread notifications -->
                        <div class="relative inline-block mr-3" id="notification-icon">
                            <i class="fas fa-envelope text-xl cursor-pointer px-2"></i>
                            <div id="notification-dropdown" class="absolute right-0 mt-2 w-64 bg-white rounded shadow-md hidden z-50 max-h-64 overflow-y-auto">
                                <ul class="py-2 text-black" id="notification-list"></ul>
                            </div>
                            {% if has_unread_notifications %}
                                <span class="absolute top-0 right-0 w-3 h-3 bg-red-500 rounded-full border-2 border-white"></span>
                            {% endif %}
                        </div>
                        

                    {% elif session['userType'] == 'staff' %}
                        <a href="{{ url_for('movies.viewBookings') }}" class="hover:bg-gray-600 hover:bg-opacity-50 px-3 py-2 rounded transition">All bookings</a>

                    {% elif session['userType'] == 'admin' %}
                        <a href="{{ url_for('movies.addMovie') }}" class="hover:bg-gray-600 hover:bg-opacity-50 px-3 py-2 rounded transition">Add a movie</a>
                        <a href="{{ url_for('movies.cancelMovie') }}" class="hover:bg-gray-600 hover:bg-opacity-50 px-3 py-2 rounded transition">Cancel a movie</a>
                    {% endif %}
                    
                    <a href="{{ url_for('auth.logout') }}" class="hover:bg-gray-600 hover:bg-opacity-50 px-3 py-2 rounded transition">Logout</a>
                {% else %}
                    <a href="{{ url_for('auth.login') }}" class="hover:bg-gray-600 hover:bg-opacity-50 px-3 py-2 rounded transition">Login</a>
                    <a href="{{ url_for('auth.signup') }}" class="hover:bg-gray-600 hover:bg-opacity-50 px-3 py-2 rounded transition">Sign up</a>
                {% endif %}
            </div>
        </div>
    </div>
</nav>


<!-- Flashed Messages -->
{% if not hide_flash_messages %}
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
        <div class="container mx-auto mt-4">
        {% for category, message in messages %}
            {% if category == 'success' %}
                <div class="bg-green-100 border-t-4 border-green-500 rounded-b text-green-900 px-4 py-3 shadow-md" role="alert">
            {% elif category == 'error' %}
                <div class="bg-red-100 border-t-4 border-red-500 rounded-b text-red-900 px-4 py-3 shadow-md" role="alert">
            {% else %}
                <!-- Default style for other types of messages -->
                <div class="bg-blue-100 border-t-4 border-blue-500 rounded-b text-blue-900 px-4 py-3 shadow-md" role="alert">
            {% endif %}
                <div class="flex">
                    <div class="py-1">
                        <svg class="fill-current h-6 w-6 mr-4" 
                             xmlns="http://www.w3.org/2000/svg" 
                             viewBox="0 0 20 20">
                             <path d="M2.93 17.07A10 10 0 1 1 17.07 2.93 10 10 0 0 1 2.93 17.07zm12.73-1.41A8 8 0 1 0 4.34 4.34a8 8 0 0 0 11.32 11.32zM9 11V9h2v6H9v-4zm0-6h2v2H9V5z"/>
                        </svg>
                    </div>
                    <div>
                        <p class="font-bold">{{ message }}</p>
                    </div>
                </div>
                </div>
        {% endfor %}
        </div>
    {% endif %}
    {% endwith %}
{% endif %}




  {% block content %}{% endblock %}


  <script>
    $(document).ready(function () {
        let userType = "{{ session['userType'] }}";

        function fetchNotifications() {
            $.getJSON("/api/get-notifications", function (data) {
                let notificationList = $("#notification-list");
                notificationList.empty();

                if (data.numberOfUnreadNotifications > 0) {
                    $("#notification-icon").find('.unread-dot').remove();
                    $("#notification-icon").append('<span class="absolute top-0 right-0 w-3 h-3 bg-red-500 rounded-full border-2 border-white unread-dot"></span>');
                } else {
                    $("#notification-icon").find('.unread-dot').remove();
                }

                if (data.notifications.length === 0) {
                    notificationList.append('<li class="px-4 py-2 text-center text-gray-500">No new notifications</li>');
                } else {
                    data.notifications.sort((a, b) => new Date(b.timestamp) - new Date(a.timestamp));

                    data.notifications.forEach(function (notification) {
                        let notificationItem = `
                <li class="px-4 py-2 hover:bg-gray-200 notification-item ${!notification.isRead ? 'bg-gray-100' : ''}" data-id="${notification.id}" data-expanded="false">
                    <a href="${notification.url}">
                        <span class="line-clamp-1">${notification.message}</span>
                    </a>
                </li>`;
                        notificationList.append(notificationItem);
                    });
                }
            });
        }

        fetchNotifications();

        $("#notification-icon .fa-envelope").click(function () {
            $("#notification-dropdown").toggle();
        });

        $(document).on("click", function (event) {
            if (!$(event.target).closest("#notification-icon").length) {
                $("#notification-dropdown").hide();
            }
        });


        $(document).on('click', '.notification-item a', function (event) {
            event.preventDefault();
            event.stopPropagation(); 

            const notificationItem = $(this).closest('.notification-item');
            const notificationId = notificationItem.data('id');
            let isExpanded = notificationItem.data('expanded');

            console.log("Before Toggle - Notification ID:", notificationId, "Is Expanded:", isExpanded);

            if (isExpanded) {
                notificationItem.find('span').removeClass('line-clamp-none').addClass('line-clamp-1');
                notificationItem.data('expanded', false);
            } else {
                notificationItem.find('span').removeClass('line-clamp-1').addClass('line-clamp-none');
                notificationItem.data('expanded', true);
            }

            isExpanded = notificationItem.data('expanded');
            console.log("After Toggle - Is Expanded:", isExpanded);

            $.post('/api/mark-notification-read', { id: notificationId }, function (response) {

                if (response.success) {
                    setTimeout(fetchNotifications, 5000);
                }
            });
        });
    });

</script>
    

</body>

</html>

app/templates/bookings.html
{% extends 'base.html' %}

{% block title %}My bookings{% endblock %}

{% block content %}

<div class="container mx-auto px-4 pt-16">

    <h2 class="text-4xl font-bold mb-8 text-center">Your Bookings</h2>

    <div class="shadow overflow-hidden rounded border-b border-gray-200">
        <table class="min-w-full bg-white">
            <thead class="bg-gray-800 text-white">
                <tr>
                    <th class="w-1/6 py-3 px-4 text-left text-xs font-semibold uppercase tracking-wider">
                        Booking ID
                    </th>
                    <th class="w-1/6 py-3 px-4 text-left text-xs font-semibold uppercase tracking-wider">
                        Created at
                    </th>
                    <th class="w-1/6 py-3 px-4 text-left text-xs font-semibold uppercase tracking-wider">
                        Movie
                    </th>
                    <th class="w-1/6 py-3 px-4 text-left text-xs font-semibold uppercase tracking-wider">
                        Date & Time
                    </th>
                    <th class="w-1/6 py-3 px-4 text-left text-xs font-semibold uppercase tracking-wider">
                        Venue
                    </th>
                    <th class="w-1/6 py-3 px-4 text-left text-xs font-semibold uppercase tracking-wider">
                        Seats
                    </th>
                    <th class="w-1/6 py-3 px-4 text-left text-xs font-semibold uppercase tracking-wider">
                        Total Amount
                    </th>
                    <th class="w-1/6 py-3 px-4 text-left text-xs font-semibold uppercase tracking-wider">
                        Status
                    </th>
                </tr>
            </thead>
            <tbody class="text-gray-700">
                {% for booking in bookingList %}
                <tr class="hover:bg-gray-100" data-screening-date="{{ booking.screening.startTime.strftime('%Y-%m-%d') }}">
                    <td class="py-4 px-6 border-b border-gray-200 items-center">{{ booking.id }}</td>
                    <td class="py-4 px-6 border-b border-gray-200 items-center">{{ booking.createdOn.strftime('%d-%m-%Y %I:%M:%S') }}</td>
                    <td class="py-4 px-6 border-b border-gray-200 items-center">{{ booking.screening.movie.title }}</td>
                    <td class="py-4 px-6 border-b border-gray-200 items-center"><span class="block">{{ booking.screening.screeningDate.strftime('%d-%m-%Y') }}</span><span class="block">{{ booking.screening.startTime.strftime('%I:%M %p') }}</span></td>
                    <td class="py-4 px-6 border-b border-gray-200 items-center">{{ booking.screening.hall.name }}</td>
                    <td class="py-4 px-6 border-b border-gray-200 items-center">{{ booking.seats|map(attribute='seatNumber')|join(", ") }}</td>
                    <td class="py-4 px-6 border-b border-gray-200 items-center">{%if booking.payment.discountedAmount%}${%else%}--{%endif%}{{ booking.payment.discountedAmount }}</td>
                    <td class="py-4 px-6 border-b border-gray-200 items-center">
                        <div class="inline-flex items-center w-full justify-between">
                        {{ booking.status.name }}
                        <div class="inline-flex">
                        {% if booking.status.name != 'CANCELLED' %}
                            <form id="cancelForm" action="{{ url_for('movies.cancelBooking', bookingId=booking.id) }}" method="post" class="ml-4">
                                <button data-cancel-button class="text-white bg-red-500 hover:bg-red-600 py-1 px-3 text-xs rounded-full">Cancel</button>
                            </form>
                            {% if booking.user.type == 'customer' and  booking.status.name == 'PENDING'%}
                            <form id="payForm" action="{{ url_for('movies.paymentOnline', bookingId=booking.id) }}" method="get" class="ml-4">
                                <button class="text-white bg-green-500 hover:bg-red-600 py-1 px-3 text-xs rounded-full">Pay</button>
                            </form>
                            {% elif booking.user.type == 'staff' and  booking.status.name == 'PENDING' %}
                            <form id="payForm" action="{{ url_for('movies.paymentOnsite', bookingId=booking.id) }}" method="get" class="ml-4">
                                <button class="text-white bg-green-500 hover:bg-red-600 py-1 px-3 text-xs rounded-full">Pay</button>
                            </form>
                            {% endif %}
                        {% endif %}
                        </div>
                        </div>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

<div id="cancelModal" class="fixed inset-0 flex items-center justify-center z-50 bg-black bg-opacity-50 hidden">
    <div class="bg-white p-4 rounded-md">
        <p>Are you sure you want to cancel this booking?</p>
        <div class="flex justify-end mt-4">
            <button id="closeModal" class="px-4 py-2 bg-gray-400 rounded-md mr-2">No</button>
            <button id="confirmCancel" class="px-4 py-2 bg-red-600 text-white rounded-md">Yes, Cancel</button>
        </div>
    </div>
</div>

<script>
    document.addEventListener("DOMContentLoaded", function() {
        const cancelButtons = document.querySelectorAll("[data-cancel-button]");
        const currentDate = new Date();
        const cancelModal = document.getElementById("cancelModal");
        const closeModal = document.getElementById("closeModal");
        const confirmCancel = document.getElementById("confirmCancel");
        let currentBookingId = null;

        cancelButtons.forEach(button => {
            button.addEventListener("click", function(event) {
                event.preventDefault();

                // Retrieve the booking ID from the button's dataset
                currentBookingId = button.dataset.bookingId;

                cancelModal.style.display = "flex";
            });
        });

        closeModal.addEventListener("click", function() {
            cancelModal.style.display = "none";
        });

        confirmCancel.addEventListener("click", function() {
            document.querySelector('#cancelForm').submit();
        });
    });
</script>

    
    
    
    
    
    
    

{% endblock %}

app/templates/cancelMovie.html
{% extends 'base.html' %}

{% block title %}screenings{% endblock %}

{% block content %}

<div class="container mx-auto mt-20 p-6 shadow-md rounded-lg max-w-4xl bg-gray-100 font-sans antialiased">
    <h2 class="text-2xl font-semibold mb-4">Cancel a Movie</h2>

    <table class="w-full table-auto">
        <thead>
            <tr>
                <th class="px-4 py-2">Movie ID</th>
                <th class="px-4 py-2">Title</th>
                <th class="px-4 py-2">Release Year</th>
                <th class="px-4 py-2">Status</th>
                <th class="px-4 py-2">Action</th>
            </tr>
        </thead>
        <tbody>
            {% for movie in movies %}
            <tr>
                <td class="border px-4 py-2">#{{ movie.id }}</td>
                <td class="border px-4 py-2">{{ movie.title }}</td>
                <td class="border px-4 py-2">{{ movie.releaseDate.strftime('%Y')  }}</td>
                <td class="border px-4 py-2">{{ movie.status.name }}</td>
                <td class="border px-4 py-2">
                    <button onclick="showModal({{ movie.id }})" class="bg-red-500 hover:bg-red-600 text-white font-bold py-2 px-4 rounded">
                        Cancel
                    </button>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

<!-- Modal structure -->
<div id="modal" class="fixed top-0 left-0 w-full h-full flex items-center justify-center bg-black bg-opacity-50 hidden">
    <div class="bg-white p-8 rounded-lg shadow-md max-w-xl max-h-[80vh] overflow-y-auto m-auto">
        <p>Are you sure you want to cancel this movie?</p>
        <form id="modalForm" action="" method="post" class="mt-4">
            <button type="submit" class="bg-red-500 hover:bg-red-600 text-white font-bold py-2 px-4 rounded mr-2">
                Confirm
            </button>
            <button type="button" onclick="hideModal()" class="bg-gray-400 hover:bg-gray-500 text-white font-bold py-2 px-4 rounded">
                Cancel
            </button>
        </form>
    </div>
</div>

<script>
    var baseURL = "{{ url_for('movies.cancelMovie', movieId='MOVIE_ID') }}";
    function showModal(movieId) {
        document.getElementById('modal').style.display = 'flex';
        var actionURL = baseURL.replace('MOVIE_ID', movieId);
        document.getElementById('modalForm').action = actionURL;
    }

    function hideModal() {
        document.getElementById('modal').style.display = 'none';
    }
</script>

{% endblock %}